// 
// This source code was auto-generated by bobflux-gen, Version=0.15.0.
// Don't modify this file but re-generate it by bobflux-gen.
// Bobflux-gen - https://www.npmjs.com/package/bobflux-gen
//

import * as s from './state';
import * as f from '../flux';

export * from './state';

export const rootKey = 'whatNext';

export const rootCursor: f.ICursor<s.IWhatNextState> = {
    key: rootKey
};

export default rootCursor;

export const sourcesCursor: f.ICursor<s.IBobrilSource[]> = {
    key: rootKey + '.sources'
};
