// 
// This source code was auto-generated by bobflux-gen, Version=0.15.0.
// Don't modify this file but re-generate it by bobflux-gen.
// Bobflux-gen - https://www.npmjs.com/package/bobflux-gen
//

import * as s from './states';
import * as f from './flux';
import * as td from './todos/state';
import * as wn from './whatNext/state';
import * as ua from './userAccount/userAccountPageStates';

export * from './states';

export const rootKey = f.rootCursor.key;

// export const rootCursor: f.ICursor<s.IApplicationState> = f.rootCursor;
export const rootCursor: f.ICursor<s.IApplicationState> = {
    key: rootKey
};

export default rootCursor;

export const todosCursor: f.ICursor<td.ITodosState> = {
    key: 'todos'
};

export const whatNextCursor: f.ICursor<wn.IWhatNextState> = {
    key: 'whatNext'
};

export const userAccountCursor: f.ICursor<ua.IUserAccountPageState> = {
    key: 'userAccount'
};

export const userInfoCursor: f.ICursor<ua.IUserInfo> = {
    key: 'userInfo'
};

export const userInfoEmailCursor: f.ICursor<string> = {
    key: 'userInfo.email'
};

export const userInfoNameCursor: f.ICursor<string> = {
    key: 'userInfo.name'
};

export const userInfoSurNameCursor: f.ICursor<string> = {
    key: 'userInfo.surName'
};
