// 
// This source code was auto-generated by bobflux-gen, Version=0.15.0.
// Don't modify this file but re-generate it by bobflux-gen.
// Bobflux-gen - https://www.npmjs.com/package/bobflux-gen
//

import * as s from '../../src/userAccount/userAccountPageStates';
import * as f from '../../src/flux';

export * from '../../src/userAccount/userAccountPageStates';

export class UserInfoBuilder {
    protected state: s.IUserInfo = s.createDefaultUserInfo();

    public withEmail(email: string): UserInfoBuilder {
        this.state.email = email;
        return this;
    };

    public withName(name: string): UserInfoBuilder {
        this.state.name = name;
        return this;
    };

    public withSurName(surName: string): UserInfoBuilder {
        this.state.surName = surName;
        return this;
    };

    public build(): s.IUserInfo {
        return this.state;
    }

    public buildToStore(): s.IUserInfo {
        f.bootstrap({ userInfo: this.state });
        return this.state;
    }
}

export function isUserInfoBuilder(obj: s.IUserInfo | UserInfoBuilder): obj is UserInfoBuilder {
    return 'build' in obj;
}
