// 
// This source code was auto-generated by bobflux-gen, Version=0.15.0.
// Don't modify this file but re-generate it by bobflux-gen.
// Bobflux-gen - https://www.npmjs.com/package/bobflux-gen
//

import * as s from '../src/states';
import * as f from '../src/flux';
import * as td from '../src/todos/state';
import * as wn from '../src/whatNext/state';
import * as ua from '../src/userAccount/userAccountPageStates';

export * from '../src/states';

export class ApplicationStateBuilder {
    protected state: s.IApplicationState = s.createDefaultApplicationState();

    public withTodos(todos: td.ITodosState): ApplicationStateBuilder {
        this.state.todos = todos;
        return this;
    };

    public withWhatNext(whatNext: wn.IWhatNextState): ApplicationStateBuilder {
        this.state.whatNext = whatNext;
        return this;
    };

    public withUserAccount(userAccount: ua.IUserAccountPageState): ApplicationStateBuilder {
        this.state.userAccount = userAccount;
        return this;
    };

    public withUserInfo(userInfo: ua.IUserInfo): ApplicationStateBuilder {
        this.state.userInfo = userInfo;
        return this;
    };

    public build(): s.IApplicationState {
        return this.state;
    }

    public buildToStore(): s.IApplicationState {
        f.bootstrap(this.state);
        return this.state;
    }
}

export function isApplicationStateBuilder(obj: s.IApplicationState | ApplicationStateBuilder): obj is ApplicationStateBuilder {
    return 'build' in obj;
}
